#!/bin/bash
# VPSの環境変数を修正するスクリプト

echo "🔧 VPSのフロントエンド環境変数を修正します..."
echo ""
echo "以下のコマンドをVPSで実行してください："
echo ""
echo "ssh root@162.43.15.173"
echo "cd /var/www/oriental-synergy/frontend"
echo ""
echo "# 環境変数ファイルを作成/更新"
echo "cat > .env.local << 'ENVEOF'"
echo "NEXT_PUBLIC_API_URL=http://162.43.15.173:8000/api/v1"
echo "NEXT_TELEMETRY_DISABLED=1"
echo "NODE_ENV=production"
echo "ENVEOF"
echo ""
echo "# フロントエンドコンテナを再ビルド（環境変数はビルド時に必要）"
echo "cd /var/www/oriental-synergy"
echo "docker-compose -f docker-compose.production.yml stop frontend"
echo "docker-compose -f docker-compose.production.yml build frontend"
echo "docker-compose -f docker-compose.production.yml up -d frontend"
echo ""
echo "# ログを確認"
echo "docker-compose -f docker-compose.production.yml logs -f frontend"
